version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm  # Asegúrate de especificar el gestor de paquetes si es necesario
      - run:
          name: Run test
          command: npm run test
      - run:
          name: Build App
          command: npm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
